default:
  SECRET_KEY: ""
  SECRET_KEY_FOR_MAIL: ""
  DEBUG: true
  ALLOWED_HOSTS: []
  DATABASE_URL: ""

heroku:
  DEBUG: false
  ALLOWED_HOSTS:
    - 127.0.0.1
    - localhost
    - searchdata.herokuapp.com
